const CATEGORIES = [
  {
    "slug": "gifting",
    "label": "Gifting",
    "icon": "\ud83c\udf81",
    "groups": [
      {
        "slug": "for-her",
        "label": "For Her",
        "leaves": [
          {
            "slug": "jewellery",
            "label": "Jewellery"
          },
          {
            "slug": "handbags",
            "label": "Handbags"
          },
          {
            "slug": "girls-perfumes",
            "label": "Girl's Perfumes"
          },
          {
            "slug": "girls-watches",
            "label": "Girl's Watches"
          },
          {
            "slug": "waterbottle",
            "label": "Waterbottle"
          }
        ]
      },
      {
        "slug": "for-him",
        "label": "For Him",
        "leaves": [
          {
            "slug": "boys-watches",
            "label": "Boy's Watches"
          },
          {
            "slug": "boys-perfumes",
            "label": "Boy's Perfumes"
          },
          {
            "slug": "wallet",
            "label": "Wallet"
          },
          {
            "slug": "waterbottle",
            "label": "Waterbottle"
          }
        ]
      }
    ]
  },
  {
    "slug": "perfume",
    "label": "Perfume",
    "icon": "\ud83e\uddf4",
    "groups": [
      {
        "slug": null,
        "label": null,
        "leaves": [
          {
            "slug": "boys-perfumes",
            "label": "Boy's Perfumes"
          },
          {
            "slug": "girls-perfumes",
            "label": "Girl's Perfumes"
          }
        ]
      }
    ]
  },
  {
    "slug": "fashion",
    "label": "Fashion",
    "icon": "\ud83d\udc57",
    "groups": [
      {
        "slug": "jewellery",
        "label": "Jewellery",
        "leaves": [
          {
            "slug": "necklace",
            "label": "Necklace"
          },
          {
            "slug": "bracelet",
            "label": "Bracelet"
          },
          {
            "slug": "earrings",
            "label": "Earrings"
          },
          {
            "slug": "anklets",
            "label": "Anklets"
          },
          {
            "slug": "rings",
            "label": "Rings"
          }
        ]
      },
      {
        "slug": "watches",
        "label": "Watches",
        "leaves": [
          {
            "slug": "girls-watches",
            "label": "Girl's Watches"
          },
          {
            "slug": "boys-watches",
            "label": "Boy's Watches"
          }
        ]
      },
      {
        "slug": null,
        "label": null,
        "leaves": [
          {
            "slug": "handbags",
            "label": "Handbags"
          },
          {
            "slug": "wallet",
            "label": "Wallet"
          }
        ]
      }
    ]
  },
  {
    "slug": "wall-decor",
    "label": "Wall Decor",
    "icon": "\ud83d\uddbc\ufe0f",
    "groups": [
      {
        "slug": null,
        "label": null,
        "leaves": [
          {
            "slug": "wall-clock",
            "label": "Wall Clock"
          },
          {
            "slug": "wall-art",
            "label": "Wall Art"
          }
        ]
      }
    ]
  },
  {
    "slug": "home-decor",
    "label": "Home Decor",
    "icon": "\ud83c\udffa",
    "groups": [
      {
        "slug": null,
        "label": null,
        "leaves": [
          {
            "slug": "showpieces",
            "label": "Showpieces"
          },
          {
            "slug": "lamp",
            "label": "Lamp"
          },
          {
            "slug": "fountain",
            "label": "Fountain"
          },
          {
            "slug": "planters",
            "label": "Planters"
          },
          {
            "slug": "frames",
            "label": "Frames"
          }
        ]
      }
    ]
  },
  {
    "slug": "crockery",
    "label": "Crockery",
    "icon": "\ud83c\udf7d\ufe0f",
    "groups": [
      {
        "slug": "premium-crockery",
        "label": "Premium Crockery",
        "leaves": [
          {
            "slug": "dinner-set",
            "label": "Dinner Set"
          },
          {
            "slug": "glasses",
            "label": "Glasses"
          },
          {
            "slug": "cup-saucer",
            "label": "Cup & Saucer"
          },
          {
            "slug": "ice-cream-set",
            "label": "Ice-Cream Set"
          }
        ]
      },
      {
        "slug": null,
        "label": null,
        "leaves": [
          {
            "slug": "melamine-crockery",
            "label": "Melamine Crockery"
          }
        ]
      }
    ]
  },
  {
    "slug": "kitchen",
    "label": "Kitchen",
    "icon": "\ud83c\udf73",
    "groups": [
      {
        "slug": null,
        "label": null,
        "leaves": [
          {
            "slug": "kitchen-utensils",
            "label": "Kitchen Utensils"
          },
          {
            "slug": "kitchen-accessories",
            "label": "Kitchen Accessories"
          },
          {
            "slug": "tiffin-lunch-boxes",
            "label": "Tiffin & Lunch Boxes"
          },
          {
            "slug": "waterbottles-kitchen",
            "label": "Waterbottles"
          }
        ]
      }
    ]
  }
];

const PRODUCTS = [
  {
    "id": 1,
    "name": "Kundan Necklace Set",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "jewellery",
    "subcategoryLabel": "Jewellery",
    "price": 1099,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 2,
    "name": "Oxidised Silver Jhumkas",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "jewellery",
    "subcategoryLabel": "Jewellery",
    "price": 1499,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 3,
    "name": "Pearl Drop Earrings",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "jewellery",
    "subcategoryLabel": "Jewellery",
    "price": 1099,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 4,
    "name": "Meenakari Bangle Set",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "jewellery",
    "subcategoryLabel": "Jewellery",
    "price": 1099,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 5,
    "name": "Temple Jewellery Set",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "jewellery",
    "subcategoryLabel": "Jewellery",
    "price": 1299,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 6,
    "name": "American Diamond Ring",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "jewellery",
    "subcategoryLabel": "Jewellery",
    "price": 1799,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 7,
    "name": "Quilted Sling Bag",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 599,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 8,
    "name": "Embroidered Potli Bag",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 549,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 9,
    "name": "Structured Tote Bag",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 1299,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 10,
    "name": "Beaded Clutch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 1199,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 11,
    "name": "Canvas Tote Bag",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 2499,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 12,
    "name": "Velvet Evening Bag",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 1999,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 13,
    "name": "Floral Eau De Parfum",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 549,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 14,
    "name": "Musk Rose Perfume",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 449,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 15,
    "name": "Citrus Bloom Perfume",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 1099,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 16,
    "name": "Vanilla Orchid Perfume",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 749,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 17,
    "name": "Jasmine Mist Perfume",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 499,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 18,
    "name": "Rose Oud Perfume",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 399,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 19,
    "name": "Rose Gold Strap Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 1499,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 20,
    "name": "Minimalist Dial Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 2499,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 21,
    "name": "Pearl Chain Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 349,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 22,
    "name": "Pastel Leather Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 1999,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 23,
    "name": "Diamond Dial Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 949,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 24,
    "name": "Mesh Strap Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 1099,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 25,
    "name": "Copper Water Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 2499,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 26,
    "name": "Insulated Steel Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 1999,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 27,
    "name": "Floral Print Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 2499,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 28,
    "name": "Matte Pastel Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 549,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 29,
    "name": "Glass Infuser Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 1999,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 30,
    "name": "Sipper Bottle with Sleeve",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-her",
    "groupLabel": "For Her",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 299,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 31,
    "name": "Leather Strap Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 1299,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 32,
    "name": "Chronograph Dial Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 399,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 33,
    "name": "Steel Bracelet Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 349,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 34,
    "name": "Matte Black Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 349,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 35,
    "name": "Classic Analog Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 599,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 36,
    "name": "Sports Dial Watch",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 649,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 37,
    "name": "Woody Musk Cologne",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 1999,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 38,
    "name": "Citrus Sport Perfume",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 299,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 39,
    "name": "Oud Intense Perfume",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 1099,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 40,
    "name": "Leather Amber Cologne",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 799,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 41,
    "name": "Fresh Aqua Perfume",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 1099,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 42,
    "name": "Spiced Vanilla Cologne",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 1799,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 43,
    "name": "Leather Bifold Wallet",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 599,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 44,
    "name": "RFID Protect Wallet",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 1299,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 45,
    "name": "Slim Cardholder Wallet",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 649,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 46,
    "name": "Embossed Leather Wallet",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 2499,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 47,
    "name": "Zip Around Wallet",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 749,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 48,
    "name": "Minimalist Wallet",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 1199,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 49,
    "name": "Steel Sports Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 299,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 50,
    "name": "Matte Black Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 2799,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 51,
    "name": "Insulated Flask Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 399,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 52,
    "name": "Gym Shaker Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 1099,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 53,
    "name": "Copper Fitness Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 2499,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 54,
    "name": "Rugged Outdoor Bottle",
    "category": "gifting",
    "categoryLabel": "Gifting",
    "group": "for-him",
    "groupLabel": "For Him",
    "subcategory": "waterbottle",
    "subcategoryLabel": "Waterbottle",
    "price": 699,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 55,
    "name": "Intense Oud Cologne",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 999,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 56,
    "name": "Citrus Woody Perfume",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 1499,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 57,
    "name": "Aqua Fresh Cologne",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 399,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 58,
    "name": "Amber Spice Perfume",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 699,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 59,
    "name": "Leather Musk Cologne",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 799,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 60,
    "name": "Classic Sandalwood Perfume",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "boys-perfumes",
    "subcategoryLabel": "Boy's Perfumes",
    "price": 649,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 61,
    "name": "Blush Rose Perfume",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 1299,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 62,
    "name": "Sweet Vanilla Mist",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 749,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 63,
    "name": "White Jasmine Perfume",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 299,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 64,
    "name": "Peony Bloom Perfume",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 399,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 65,
    "name": "Citrus Fresh Perfume",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 1799,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 66,
    "name": "Amber Musk Perfume",
    "category": "perfume",
    "categoryLabel": "Perfume",
    "group": null,
    "groupLabel": null,
    "subcategory": "girls-perfumes",
    "subcategoryLabel": "Girl's Perfumes",
    "price": 449,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 67,
    "name": "Layered Chain Necklace",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "necklace",
    "subcategoryLabel": "Necklace",
    "price": 949,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 68,
    "name": "Kundan Choker Necklace",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "necklace",
    "subcategoryLabel": "Necklace",
    "price": 449,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 69,
    "name": "Pearl Strand Necklace",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "necklace",
    "subcategoryLabel": "Necklace",
    "price": 749,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 70,
    "name": "Oxidised Statement Necklace",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "necklace",
    "subcategoryLabel": "Necklace",
    "price": 949,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 71,
    "name": "Gold Plated Necklace",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "necklace",
    "subcategoryLabel": "Necklace",
    "price": 399,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 72,
    "name": "Beaded Boho Necklace",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "necklace",
    "subcategoryLabel": "Necklace",
    "price": 299,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 73,
    "name": "Charm Chain Bracelet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "bracelet",
    "subcategoryLabel": "Bracelet",
    "price": 2799,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 74,
    "name": "Beaded Stack Bracelet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "bracelet",
    "subcategoryLabel": "Bracelet",
    "price": 299,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 75,
    "name": "Cuff Bangle Bracelet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "bracelet",
    "subcategoryLabel": "Bracelet",
    "price": 599,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 76,
    "name": "Pearl Bracelet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "bracelet",
    "subcategoryLabel": "Bracelet",
    "price": 599,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 77,
    "name": "Oxidised Cuff Bracelet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "bracelet",
    "subcategoryLabel": "Bracelet",
    "price": 349,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 78,
    "name": "Minimalist Bracelet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "bracelet",
    "subcategoryLabel": "Bracelet",
    "price": 1199,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 79,
    "name": "Jhumka Earrings",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "earrings",
    "subcategoryLabel": "Earrings",
    "price": 949,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 80,
    "name": "Stud Earrings Set",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "earrings",
    "subcategoryLabel": "Earrings",
    "price": 949,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 81,
    "name": "Tassel Drop Earrings",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "earrings",
    "subcategoryLabel": "Earrings",
    "price": 999,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 82,
    "name": "Hoop Earrings",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "earrings",
    "subcategoryLabel": "Earrings",
    "price": 399,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 83,
    "name": "Chandbali Earrings",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "earrings",
    "subcategoryLabel": "Earrings",
    "price": 1799,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 84,
    "name": "Pearl Stud Earrings",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "earrings",
    "subcategoryLabel": "Earrings",
    "price": 2499,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 85,
    "name": "Silver Ghungroo Anklet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "anklets",
    "subcategoryLabel": "Anklets",
    "price": 599,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 86,
    "name": "Beaded Anklet Set",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "anklets",
    "subcategoryLabel": "Anklets",
    "price": 2799,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 87,
    "name": "Oxidised Anklet Pair",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "anklets",
    "subcategoryLabel": "Anklets",
    "price": 699,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 88,
    "name": "Charm Anklet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "anklets",
    "subcategoryLabel": "Anklets",
    "price": 799,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 89,
    "name": "Layered Anklet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "anklets",
    "subcategoryLabel": "Anklets",
    "price": 399,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 90,
    "name": "Pearl Anklet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "anklets",
    "subcategoryLabel": "Anklets",
    "price": 749,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 91,
    "name": "Adjustable Stone Ring",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "rings",
    "subcategoryLabel": "Rings",
    "price": 799,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 92,
    "name": "Kundan Cocktail Ring",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "rings",
    "subcategoryLabel": "Rings",
    "price": 299,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 93,
    "name": "Stacking Ring Set",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "rings",
    "subcategoryLabel": "Rings",
    "price": 999,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 94,
    "name": "Oxidised Statement Ring",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "rings",
    "subcategoryLabel": "Rings",
    "price": 449,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 95,
    "name": "Pearl Ring",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "rings",
    "subcategoryLabel": "Rings",
    "price": 499,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 96,
    "name": "Minimalist Band Ring",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "jewellery",
    "groupLabel": "Jewellery",
    "subcategory": "rings",
    "subcategoryLabel": "Rings",
    "price": 649,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 97,
    "name": "Rose Gold Chain Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 449,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 98,
    "name": "Slim Dial Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 299,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 99,
    "name": "Pastel Strap Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 349,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 100,
    "name": "Bracelet Style Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 1099,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 101,
    "name": "Diamond Case Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 1199,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 102,
    "name": "Everyday Analog Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "girls-watches",
    "subcategoryLabel": "Girl's Watches",
    "price": 549,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 103,
    "name": "Steel Chronograph Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 2799,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 104,
    "name": "Matte Leather Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 1499,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 105,
    "name": "Sports Analog Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 599,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 106,
    "name": "Classic Dress Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 1099,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 107,
    "name": "Bracelet Link Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 1299,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 108,
    "name": "Minimal Dial Watch",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": "watches",
    "groupLabel": "Watches",
    "subcategory": "boys-watches",
    "subcategoryLabel": "Boy's Watches",
    "price": 599,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 109,
    "name": "Structured Satchel Bag",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 499,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 110,
    "name": "Sling Crossbody Bag",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 999,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 111,
    "name": "Woven Tote Bag",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 2499,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 112,
    "name": "Everyday Shoulder Bag",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 949,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 113,
    "name": "Mini Handbag",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 449,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 114,
    "name": "Office Tote Bag",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "handbags",
    "subcategoryLabel": "Handbags",
    "price": 949,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 115,
    "name": "Bifold Leather Wallet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 999,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 116,
    "name": "Long Zip Wallet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 599,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 117,
    "name": "Card Holder Wallet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 299,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 118,
    "name": "Textured Wallet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 699,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 119,
    "name": "Compact Wallet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 1799,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 120,
    "name": "Classic Leather Wallet",
    "category": "fashion",
    "categoryLabel": "Fashion",
    "group": null,
    "groupLabel": null,
    "subcategory": "wallet",
    "subcategoryLabel": "Wallet",
    "price": 749,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 121,
    "name": "Wooden Round Wall Clock",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-clock",
    "subcategoryLabel": "Wall Clock",
    "price": 299,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 122,
    "name": "Minimalist Wall Clock",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-clock",
    "subcategoryLabel": "Wall Clock",
    "price": 599,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 123,
    "name": "Vintage Numeral Clock",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-clock",
    "subcategoryLabel": "Wall Clock",
    "price": 549,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 124,
    "name": "Metal Frame Wall Clock",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-clock",
    "subcategoryLabel": "Wall Clock",
    "price": 949,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 125,
    "name": "Silent Sweep Wall Clock",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-clock",
    "subcategoryLabel": "Wall Clock",
    "price": 1999,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 126,
    "name": "Boho Wall Clock",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-clock",
    "subcategoryLabel": "Wall Clock",
    "price": 2499,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 127,
    "name": "Abstract Canvas Art",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-art",
    "subcategoryLabel": "Wall Art",
    "price": 1799,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 128,
    "name": "Botanical Wall Print",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-art",
    "subcategoryLabel": "Wall Art",
    "price": 449,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 129,
    "name": "Line Art Print Set",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-art",
    "subcategoryLabel": "Wall Art",
    "price": 349,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 130,
    "name": "Boho Tapestry Art",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-art",
    "subcategoryLabel": "Wall Art",
    "price": 499,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 131,
    "name": "Framed Quote Art",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-art",
    "subcategoryLabel": "Wall Art",
    "price": 599,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 132,
    "name": "Textured Wall Panel",
    "category": "wall-decor",
    "categoryLabel": "Wall Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "wall-art",
    "subcategoryLabel": "Wall Art",
    "price": 1099,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 133,
    "name": "Ceramic Elephant Showpiece",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "showpieces",
    "subcategoryLabel": "Showpieces",
    "price": 699,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 134,
    "name": "Brass Buddha Statue",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "showpieces",
    "subcategoryLabel": "Showpieces",
    "price": 299,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 135,
    "name": "Resin Owl Showpiece",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "showpieces",
    "subcategoryLabel": "Showpieces",
    "price": 1999,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 136,
    "name": "Marble Horse Showpiece",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "showpieces",
    "subcategoryLabel": "Showpieces",
    "price": 799,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 137,
    "name": "Decorative Globe Showpiece",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "showpieces",
    "subcategoryLabel": "Showpieces",
    "price": 749,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 138,
    "name": "Metal Bird Showpiece",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "showpieces",
    "subcategoryLabel": "Showpieces",
    "price": 949,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 139,
    "name": "Ceramic Table Lamp",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "lamp",
    "subcategoryLabel": "Lamp",
    "price": 399,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 140,
    "name": "Rattan Floor Lamp",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "lamp",
    "subcategoryLabel": "Lamp",
    "price": 399,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 141,
    "name": "Himalayan Salt Lamp",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "lamp",
    "subcategoryLabel": "Lamp",
    "price": 399,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 142,
    "name": "Wooden Base Lamp",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "lamp",
    "subcategoryLabel": "Lamp",
    "price": 599,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 143,
    "name": "Fabric Shade Lamp",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "lamp",
    "subcategoryLabel": "Lamp",
    "price": 1799,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 144,
    "name": "Brass Table Lamp",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "lamp",
    "subcategoryLabel": "Lamp",
    "price": 2499,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 145,
    "name": "Tabletop Zen Fountain",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "fountain",
    "subcategoryLabel": "Fountain",
    "price": 649,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 146,
    "name": "Ceramic Tiered Fountain",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "fountain",
    "subcategoryLabel": "Fountain",
    "price": 299,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 147,
    "name": "Buddha Water Fountain",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "fountain",
    "subcategoryLabel": "Fountain",
    "price": 1999,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 148,
    "name": "LED Wall Fountain",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "fountain",
    "subcategoryLabel": "Fountain",
    "price": 899,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 149,
    "name": "Stone Finish Fountain",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "fountain",
    "subcategoryLabel": "Fountain",
    "price": 899,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 150,
    "name": "Mini Desktop Fountain",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "fountain",
    "subcategoryLabel": "Fountain",
    "price": 1999,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 151,
    "name": "Ceramic Hanging Planter",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "planters",
    "subcategoryLabel": "Planters",
    "price": 1099,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 152,
    "name": "Terracotta Planter Set",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "planters",
    "subcategoryLabel": "Planters",
    "price": 499,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 153,
    "name": "Macrame Planter",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "planters",
    "subcategoryLabel": "Planters",
    "price": 1799,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 154,
    "name": "Concrete Cube Planter",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "planters",
    "subcategoryLabel": "Planters",
    "price": 1199,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 155,
    "name": "Self-Watering Planter",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "planters",
    "subcategoryLabel": "Planters",
    "price": 1799,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 156,
    "name": "Woven Rattan Planter",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "planters",
    "subcategoryLabel": "Planters",
    "price": 499,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 157,
    "name": "Wooden Photo Frame",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "frames",
    "subcategoryLabel": "Frames",
    "price": 949,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 158,
    "name": "Collage Wall Frame",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "frames",
    "subcategoryLabel": "Frames",
    "price": 549,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 159,
    "name": "Vintage Ornate Frame",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "frames",
    "subcategoryLabel": "Frames",
    "price": 2499,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 160,
    "name": "Minimalist Photo Frame",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "frames",
    "subcategoryLabel": "Frames",
    "price": 499,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 161,
    "name": "Multi-Photo Frame Set",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "frames",
    "subcategoryLabel": "Frames",
    "price": 749,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 162,
    "name": "Floating Glass Frame",
    "category": "home-decor",
    "categoryLabel": "Home Decor",
    "group": null,
    "groupLabel": null,
    "subcategory": "frames",
    "subcategoryLabel": "Frames",
    "price": 649,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 163,
    "name": "Stoneware Dinner Set 16pc",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "dinner-set",
    "subcategoryLabel": "Dinner Set",
    "price": 1999,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 164,
    "name": "Bone China Dinner Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "dinner-set",
    "subcategoryLabel": "Dinner Set",
    "price": 649,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 165,
    "name": "Floral Print Dinner Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "dinner-set",
    "subcategoryLabel": "Dinner Set",
    "price": 599,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 166,
    "name": "Matte Finish Dinner Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "dinner-set",
    "subcategoryLabel": "Dinner Set",
    "price": 549,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 167,
    "name": "Classic White Dinner Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "dinner-set",
    "subcategoryLabel": "Dinner Set",
    "price": 2499,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 168,
    "name": "Embossed Dinner Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "dinner-set",
    "subcategoryLabel": "Dinner Set",
    "price": 1499,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 169,
    "name": "Crystal Cut Glass Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "glasses",
    "subcategoryLabel": "Glasses",
    "price": 599,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 170,
    "name": "Coloured Tumbler Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "glasses",
    "subcategoryLabel": "Glasses",
    "price": 2799,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 171,
    "name": "Highball Glass Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "glasses",
    "subcategoryLabel": "Glasses",
    "price": 949,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 172,
    "name": "Etched Glass Tumblers",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "glasses",
    "subcategoryLabel": "Glasses",
    "price": 1199,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 173,
    "name": "Stemless Wine Glass Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "glasses",
    "subcategoryLabel": "Glasses",
    "price": 1999,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 174,
    "name": "Everyday Glass Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "glasses",
    "subcategoryLabel": "Glasses",
    "price": 399,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 175,
    "name": "Bone China Cup & Saucer",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "cup-saucer",
    "subcategoryLabel": "Cup & Saucer",
    "price": 999,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 176,
    "name": "Floral Cup & Saucer Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "cup-saucer",
    "subcategoryLabel": "Cup & Saucer",
    "price": 349,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 177,
    "name": "Gold Rim Cup & Saucer",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "cup-saucer",
    "subcategoryLabel": "Cup & Saucer",
    "price": 449,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 178,
    "name": "Ceramic Cup & Saucer Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "cup-saucer",
    "subcategoryLabel": "Cup & Saucer",
    "price": 449,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 179,
    "name": "Vintage Cup & Saucer",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "cup-saucer",
    "subcategoryLabel": "Cup & Saucer",
    "price": 349,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 180,
    "name": "Pastel Cup & Saucer Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "cup-saucer",
    "subcategoryLabel": "Cup & Saucer",
    "price": 1299,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 181,
    "name": "Ceramic Ice-Cream Bowl Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "ice-cream-set",
    "subcategoryLabel": "Ice-Cream Set",
    "price": 699,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 182,
    "name": "Glass Sundae Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "ice-cream-set",
    "subcategoryLabel": "Ice-Cream Set",
    "price": 649,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 183,
    "name": "Printed Ice-Cream Cups",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "ice-cream-set",
    "subcategoryLabel": "Ice-Cream Set",
    "price": 949,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 184,
    "name": "Stainless Ice-Cream Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "ice-cream-set",
    "subcategoryLabel": "Ice-Cream Set",
    "price": 699,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 185,
    "name": "Colourful Ice-Cream Bowls",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "ice-cream-set",
    "subcategoryLabel": "Ice-Cream Set",
    "price": 999,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 186,
    "name": "Footed Ice-Cream Cups",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": "premium-crockery",
    "groupLabel": "Premium Crockery",
    "subcategory": "ice-cream-set",
    "subcategoryLabel": "Ice-Cream Set",
    "price": 1999,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 187,
    "name": "Melamine Dinner Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": null,
    "groupLabel": null,
    "subcategory": "melamine-crockery",
    "subcategoryLabel": "Melamine Crockery",
    "price": 1199,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 188,
    "name": "Melamine Snack Plates",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": null,
    "groupLabel": null,
    "subcategory": "melamine-crockery",
    "subcategoryLabel": "Melamine Crockery",
    "price": 749,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 189,
    "name": "Melamine Serving Bowls",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": null,
    "groupLabel": null,
    "subcategory": "melamine-crockery",
    "subcategoryLabel": "Melamine Crockery",
    "price": 1299,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 190,
    "name": "Melamine Lunch Plates",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": null,
    "groupLabel": null,
    "subcategory": "melamine-crockery",
    "subcategoryLabel": "Melamine Crockery",
    "price": 549,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 191,
    "name": "Melamine Curry Bowls",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": null,
    "groupLabel": null,
    "subcategory": "melamine-crockery",
    "subcategoryLabel": "Melamine Crockery",
    "price": 399,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 192,
    "name": "Melamine Platter Set",
    "category": "crockery",
    "categoryLabel": "Crockery",
    "group": null,
    "groupLabel": null,
    "subcategory": "melamine-crockery",
    "subcategoryLabel": "Melamine Crockery",
    "price": 499,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 193,
    "name": "Steel Cooking Spoon Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-utensils",
    "subcategoryLabel": "Kitchen Utensils",
    "price": 649,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 194,
    "name": "Wooden Utensil Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-utensils",
    "subcategoryLabel": "Kitchen Utensils",
    "price": 1199,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 195,
    "name": "Silicone Spatula Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-utensils",
    "subcategoryLabel": "Kitchen Utensils",
    "price": 1499,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 196,
    "name": "Non-stick Cookware Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-utensils",
    "subcategoryLabel": "Kitchen Utensils",
    "price": 2499,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 197,
    "name": "Cast Iron Tawa",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-utensils",
    "subcategoryLabel": "Kitchen Utensils",
    "price": 1999,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 198,
    "name": "Multi-purpose Ladle Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-utensils",
    "subcategoryLabel": "Kitchen Utensils",
    "price": 1999,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 199,
    "name": "Ceramic Spice Jar Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-accessories",
    "subcategoryLabel": "Kitchen Accessories",
    "price": 399,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 200,
    "name": "Kitchen Towel Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-accessories",
    "subcategoryLabel": "Kitchen Accessories",
    "price": 699,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 201,
    "name": "Glass Storage Jar Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-accessories",
    "subcategoryLabel": "Kitchen Accessories",
    "price": 599,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 202,
    "name": "Cotton Apron",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-accessories",
    "subcategoryLabel": "Kitchen Accessories",
    "price": 599,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 203,
    "name": "Kitchen Organiser Rack",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-accessories",
    "subcategoryLabel": "Kitchen Accessories",
    "price": 299,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 204,
    "name": "Oil Dispenser Bottle",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "kitchen-accessories",
    "subcategoryLabel": "Kitchen Accessories",
    "price": 399,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 205,
    "name": "Steel Lunch Box Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "tiffin-lunch-boxes",
    "subcategoryLabel": "Tiffin & Lunch Boxes",
    "price": 699,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 206,
    "name": "Insulated Tiffin Box",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "tiffin-lunch-boxes",
    "subcategoryLabel": "Tiffin & Lunch Boxes",
    "price": 999,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 207,
    "name": "Compartment Lunch Box",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "tiffin-lunch-boxes",
    "subcategoryLabel": "Tiffin & Lunch Boxes",
    "price": 1099,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 208,
    "name": "Kids Lunch Box",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "tiffin-lunch-boxes",
    "subcategoryLabel": "Tiffin & Lunch Boxes",
    "price": 649,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 209,
    "name": "Leak-Proof Tiffin Box",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "tiffin-lunch-boxes",
    "subcategoryLabel": "Tiffin & Lunch Boxes",
    "price": 349,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 210,
    "name": "Stackable Tiffin Set",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "tiffin-lunch-boxes",
    "subcategoryLabel": "Tiffin & Lunch Boxes",
    "price": 349,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  },
  {
    "id": 211,
    "name": "Steel Fridge Bottle",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "waterbottles-kitchen",
    "subcategoryLabel": "Waterbottles",
    "price": 549,
    "swatch": "swatch-1",
    "badge": "Bestseller"
  },
  {
    "id": 212,
    "name": "Insulated Family Bottle",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "waterbottles-kitchen",
    "subcategoryLabel": "Waterbottles",
    "price": 749,
    "swatch": "swatch-2",
    "badge": "New"
  },
  {
    "id": 213,
    "name": "Copper Kitchen Bottle",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "waterbottles-kitchen",
    "subcategoryLabel": "Waterbottles",
    "price": 899,
    "swatch": "swatch-3",
    "badge": "Gift Ready"
  },
  {
    "id": 214,
    "name": "Glass Water Bottle",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "waterbottles-kitchen",
    "subcategoryLabel": "Waterbottles",
    "price": 1299,
    "swatch": "swatch-4",
    "badge": null
  },
  {
    "id": 215,
    "name": "Kids Water Bottle",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "waterbottles-kitchen",
    "subcategoryLabel": "Waterbottles",
    "price": 1799,
    "swatch": "swatch-1",
    "badge": null
  },
  {
    "id": 216,
    "name": "Sports Water Bottle",
    "category": "kitchen",
    "categoryLabel": "Kitchen",
    "group": null,
    "groupLabel": null,
    "subcategory": "waterbottles-kitchen",
    "subcategoryLabel": "Waterbottles",
    "price": 499,
    "swatch": "swatch-2",
    "badge": "Bestseller"
  }
];
